api/urls.py
from django.urls import path
from api import views

app_name = "api"
urlpatterns = [

]

core/urls.py
from django.urls import path
from core import views



app_name = "core"


urlpatterns = [
    path('list1/city/', views.List1.as_view(), name="list1"),
    path('create1/city/',views.CreateCity.as_view(), name="create1"),
    path('detail/city/<int:pk>/', views.DetailCity.as_view(), name= "detail1"),
    path('update/city/<int:pk>/', views.UpdateCity.as_view(), name= "update1"),
    path('delete/city/<int:pk>/', views.DeleteCity.as_view(), name= "delete1"),

    path('list2/team/', views.List2.as_view(), name="list2"),
    path('create2/team/',views.CreateTeam.as_view(), name="create2"),
    path('detail/team/<int:pk>/', views.DetailTeam.as_view(), name= "detail2"),
    path('update/team/<int:pk>/', views.UpdateTeam.as_view(), name= "update2"),
    path('delete/team/<int:pk>/', views.DeleteTeam.as_view(), name= "delete2"),

    path('list3/stadium/', views.List3.as_view(), name="list3"),
    path('create3/stadium/',views.CreateStadium.as_view(), name="create3"),
    path('detail/stadium/<int:pk>/', views.DetailStadium.as_view(), name= "detail3"),
    path('update/stadium/<int:pk>/', views.UpdateStadium.as_view(), name= "update3"),
    path('delete/stadium/<int:pk>/', views.DeleteStadium.as_view(), name= "delete3"),
    
]

examen2/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <style TYPE="text/css">
    .menu { background-color: rgb(224, 160, 64);}
  </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"></head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <nav class="navbar navbar-expand-lg bg-body-tertiary ">
                    <div class="container-fluid menu">
                      <a class="navbar-brand" href="#">NFL</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Listas
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:list2' %}">Equipos</a></li>
                              <li><a class="dropdown-item" href="{% url 'core:list3' %}">En estadios</a></li>
                              <li><a class="dropdown-item" href="{% url 'core:list1' %}">En ciudades</a></li>
                            </ul>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled" aria-disabled="true"></a>
                          </li>
                        </ul>
                        <form class="d-flex" role="search">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                      </div>
                    </div>
                  </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-2">

            </div>
            <div class="col-10">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <!-- Footer -->
                <footer class="text-center text-lg-start bg-light text-muted">
                    <!-- Section: Social media -->
                    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
                    <!-- Left -->
                    <div class="me-5 d-none d-lg-block">
                        <span>Conoce mas acerca de nosotros</span>
                    </div>
                    <!-- Left -->
                
                    <!-- Right -->
                    <div>
                        <a href="" class="me-4 text-reset">
                        <i class="fab fa-facebook-f"></i>
                        </a>
                        <a href="" class="me-4 text-reset">
                        <i class="fab fa-twitter"></i>
                        </a>
                        <a href="" class="me-4 text-reset">
                        <i class="fab fa-google"></i>
                        </a>
                        <a href="" class="me-4 text-reset">
                        <i class="fab fa-instagram"></i>
                        </a>
                        <a href="" class="me-4 text-reset">
                        <i class="fab fa-linkedin"></i>
                        </a>
                        <a href="" class="me-4 text-reset">
                        <i class="fab fa-github"></i>
                        </a>
                    </div>
                    <!-- Right -->
                    </section>
                    <!-- Section: Social media -->
                    
                    <!-- Section: Links  -->
                    <section class="">
                    <div class="container text-center text-md-start mt-5">
                        <!-- Grid row -->
                        <div class="row mt-3">
                        <!-- Grid column -->
                        <div>
                            <!-- Content -->
                            <h6>
                            <i ></i>
                            </h6>
                            <p>
                              Esta Liga de Fútbol Americano está formada por la Conferencia Nacional (NFC) y la Conferencia Americana (AFC). 
                              Ambas son integradas por cuatro divisiones (norte, sur, este y oeste) y cada división tiene un total de cuatro equipos.

                              Cada equipo se enfrenta con los otros rivales de su misma división. Los enfrentamientos se eligen mediante un sorteo 
                              al inicio de cada temporada.
                            </p>
                        </div>
                        <!-- Grid column -->
                
                        <!-- Grid column -->
                        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                            <!-- Links -->
                            <h6 class="text-uppercase fw-bold mb-4">

                            </p>
                        </div>
                        <!-- Grid column -->
                
                        <!-- Grid column -->
                      
                        <!-- Grid column -->
                
                        <!-- Grid column -->
                        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                            <!-- Links -->
                           
                        <!-- Grid column -->
                        </div>
                        <!-- Grid row -->
                    </div>
                    </section>
                    <!-- Section: Links  -->
                
                    <!-- Copyright -->
                    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
                    NFL:
                    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
                    </div>
                    <!-- Copyright -->
                </footer>
                <!-- Footer -->   
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script></body>
</html>