api/urls.py
from django.urls import path
from api import views

app_name = "api"
urlpatterns = [

]

core/urls.py
from django.urls import path
from core import views



app_name = "core"


urlpatterns = [
    path('list1/city/', views.List1.as_view(), name="list1"),
    path('create1/city/',views.CreateCity.as_view(), name="create1"),
    path('detail/city/<int:pk>/', views.DetailCity.as_view(), name= "detail1"),
    path('update/city/<int:pk>/', views.UpdateCity.as_view(), name= "update1"),
    path('delete/city/<int:pk>/', views.DeleteCity.as_view(), name= "delete1"),

    path('list2/team/', views.List2.as_view(), name="list2"),
    path('create2/team/',views.CreateTeam.as_view(), name="create2"),
    path('detail/team/<int:pk>/', views.DetailTeam.as_view(), name= "detail2"),
    path('update/team/<int:pk>/', views.UpdateTeam.as_view(), name= "update2"),
    path('delete/team/<int:pk>/', views.DeleteTeam.as_view(), name= "delete2"),

    path('list3/stadium/', views.List3.as_view(), name="list3"),
    path('create3/stadium/',views.CreateStadium.as_view(), name="create3"),
    path('detail/stadium/<int:pk>/', views.DetailStadium.as_view(), name= "detail3"),
    path('update/stadium/<int:pk>/', views.UpdateStadium.as_view(), name= "update3"),
    path('delete/stadium/<int:pk>/', views.DeleteStadium.as_view(), name= "delete3"),
    
]

examen2/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

# @receiver(post_save, sender=GrantGoal)
# def end_time_grantgoal(sender, instance, **kwargs):
#     if instance.final_date is None or instance.final_date=='':
#         instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
#         instance.save()

#### ISSUES ####

class City(models.Model):
    name1 = models.CharField(max_length=128, default="city name")

    def __str__(self):
        return self.name1


class Team(models.Model):
    name2 = models.CharField(max_length=128, default="team name")
    description = models.CharField(max_length=256, default="team Description")
  
    def __str__(self):
        return self.name2
    
class Stadium(models.Model):
    name3 = models.CharField(max_length=128, default="stadium name")
    description2 = models.CharField(max_length=256, default="stadium Description")
    location = models.CharField(max_length=256, default="stadium location")

  
    def __str__(self):
        return self.name3
      

core/forms.py
from django import forms
from .models import *


#CITIES

class Cityform(forms.ModelForm):
    class Meta:
        model = City
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Whrite name of the City"}),
            }

class UpdateCityform(forms.ModelForm):
    class Meta:
        model = City
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Whrite name of the City"}),
            }
#TEAMS
class Teamform(forms.ModelForm):
    class Meta:
        model = Team
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Whrite name of the team"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "rows":3, "placeholder":"whhrite the description"}),
            }
        
class UpdateTeamform(forms.ModelForm):
    class Meta:
        model = Team
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Whrite name of the team"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "rows":3, "placeholder":"whhrite the description"}),
            }

#STADIUMS
class Stadiumform(forms.ModelForm):
    class Meta:
        model = Stadium
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Whrite name of the team"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "rows":3, "placeholder":"whhrite the description"}),
            "location": forms.Textarea(attrs={"type":"text", "class":"form-control", "rows":3, "placeholder":"whhrite the description"}),

            }
        
class UpdateStadiumform(forms.ModelForm):
    class Meta:
        model = Stadium
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Whrite name of the team"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "rows":3, "placeholder":"whhrite the description"}),
            "location": forms.Textarea(attrs={"type":"text", "class":"form-control", "rows":3, "placeholder":"whhrite the description"}),
            }

core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import *
from .forms import *
# Create your views here.

###### C I T Y
class CreateCity(generic.CreateView):
    template_name = "core/create1.html"
    model= City
    form_class = Cityform
    success_url = reverse_lazy("core:list1")



class List1(generic.View):
    template_name = "core/list1.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = City.objects.filter()
        self.context = {
            "city": queryset
        }
        return render(request, self.template_name, self.context)

class UpdateCity(generic.UpdateView):
    template_name = "core/update1.html"
    model = City
    form_class = UpdateCityform
    success_url = reverse_lazy("core:list1")

   
class DeleteCity(generic.DeleteView):
    template_name = "core/delete1.html"
    model = City
    success_url = reverse_lazy("core:list1")

class DetailCity(generic.DetailView):
    template_name = "core/detail1.html"
    model = City

### T E A M S
class CreateTeam(generic.CreateView):
    template_name = "core/create2.html"
    model= Team
    form_class = Teamform
    success_url = reverse_lazy("core:list2")



class List2(generic.View):
    template_name = "core/list2.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Team.objects.filter()
        self.context = {
            "team": queryset
        }
        return render(request, self.template_name, self.context)

class UpdateTeam(generic.UpdateView):
    template_name = "core/update2.html"
    model = Team
    form_class = UpdateTeamform
    success_url = reverse_lazy("core:list2")

   
class DeleteTeam(generic.DeleteView):
    template_name = "core/delete2.html"
    model = Team
    success_url = reverse_lazy("core:list2")

class DetailTeam(generic.DetailView):
    template_name = "core/detail2.html"
    model = Team

###STADIUMS
class CreateStadium(generic.CreateView):
    template_name = "core/create3.html"
    model= Stadium
    form_class = Stadiumform
    success_url = reverse_lazy("core:list3")



class List3(generic.View):
    template_name = "core/list3.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Stadium.objects.filter()
        self.context = {
            "stadium": queryset
        }
        return render(request, self.template_name, self.context)

class UpdateStadium(generic.UpdateView):
    template_name = "core/update3.html"
    model = Stadium
    form_class = UpdateStadiumform
    success_url = reverse_lazy("core:list3")

   
class DeleteStadium(generic.DeleteView):
    template_name = "core/delete3.html"
    model = Stadium
    success_url = reverse_lazy("core:list3")

class DetailStadium(generic.DetailView):
    template_name = "core/detail3.html"
    model = Stadium

templates/core/create1.html
{% extends "base/base.html" %}

{% block title %}
  CREATE CITY
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Create city</button>
        <a href="{% url 'core:list1' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/create2.html
{% extends "base/base.html" %}

{% block title %}
  CREATE TEAM
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Create team</button>
        <a href="{% url 'core:list2' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/create3.html
{% extends "base/base.html" %}

{% block title %}
  CREATE STADIUM
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Create stadium</button>
        <a href="{% url 'core:list3' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/delete1.html
{% extends "base/base.html" %}

{% block title %}
  DELETE CITY
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Realmente deseas Eliminar al GrantGoal: {{ object }}?
        <button type="submit" class="btn btn-outline-danger">Delete city</button>
        <a href="{% url 'core:list1'%}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/delete2.html
{% extends "base/base.html" %}

{% block title %}
  DELETE TEAM
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Realmente deseas Eliminar al equipo: {{ object }}?
        <button type="submit" class="btn btn-outline-danger">Delete team</button>
        <a href="{% url 'core:list2'%}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/delete3.html
{% extends "base/base.html" %}

{% block title %}
  DELETE STADIUM
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Realmente deseas Eliminar el estadio: {{ object }}?
        <button type="submit" class="btn btn-outline-danger">Delete stadium</button>
        <a href="{% url 'core:list3'%}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/detail1.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL GRANTGOAL VIEW
{% endblock title %}


{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ object.gg_title }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the grantgoal: {{ object.gg_title }} .</strong> <br>
          Grantgoal Description: {{ object.description }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the timestamp {{ object.timestamp }} to grantgoal {{ object.gg_title }} </strong> with Duration {{ object.days_duration }} days, The Deadline grantgoal is: {{ object.final_date }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Grant Goal
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the status {{ object.status }} for the {{ object.gg_title }} </strong> Its state is: {{ object.state }}
        </div>
      </div>
    </div>
  </div>
  
  <a href="{% url 'core:list1' %}">back to list</a>
{% endblock content %}

templates/core/detail2.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL TEAM
{% endblock title %}


{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ object.gg_title }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the grantgoal: {{ object.gg_title }} .</strong> <br>
          Grantgoal Description: {{ object.description }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the timestamp {{ object.timestamp }} to grantgoal {{ object.gg_title }} </strong> with Duration {{ object.days_duration }} days, The Deadline grantgoal is: {{ object.final_date }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Grant Goal
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the status {{ object.status }} for the {{ object.gg_title }} </strong> Its state is: {{ object.state }}
        </div>
      </div>
    </div>
  </div>
  
  <a href="{% url 'core:list2' %}">back to list</a>
{% endblock content %}

templates/core/detail3.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL STADIUM
{% endblock title %}


{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ object.gg_title }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the grantgoal: {{ object.gg_title }} .</strong> <br>
          Grantgoal Description: {{ object.description }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the timestamp {{ object.timestamp }} to grantgoal {{ object.gg_title }} </strong> with Duration {{ object.days_duration }} days, The Deadline grantgoal is: {{ object.final_date }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Grant Goal
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the status {{ object.status }} for the {{ object.gg_title }} </strong> Its state is: {{ object.state }}
        </div>
      </div>
    </div>
  </div>
  
  <a href="{% url 'core:list3' %}">back to list</a>
{% endblock content %}

templates/core/list1.html
{% extends 'base/base.html' %}

{% block title %} LIST CITY{% endblock title %}

{% block content %}


    <a href="{% url 'core:create1' %}" class="btn btn-outline-success form-control">add city</a>
    <table class="table table-striped table-hover">
        <thead>
            
            <th>NAME CITY</th>
            
        </thead>
        <tbody>
            {% for city in city%}
                <tr>
                    <td>{{ city.name1 }}</td>
                    
                    <td><a href="{% url 'core:detail1' city.id %}" class="btn btn-outline-info"> Detail </a></td>
                    <td><a href="{% url 'core:update1' city.id %}" class="btn btn-outline-warning"> Update</a></td>
                    <td><a href="{% url 'core:delete1' city.id %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

templates/core/list2.html
{% extends 'base/base.html' %}

{% block title %} LIST TEAM{% endblock title %}

{% block content %}


    <a href="{% url 'core:create2' %}" class="btn btn-outline-success form-control">add team</a>
    <table class="table table-striped table-hover">
        <thead>
            
            <th>NAME TEAM</th>
            <th>DESCRIPTION</th> 
        </thead>
        <tbody>
            {% for team in team %}
                <tr>
                    <td>{{ team.name2 }}</td>
                    <td>{{ team.description }}</td>
                   
                    <td><a href="{% url 'core:detail2' team.id %}" class="btn btn-outline-info"> Detail </a></td>
                    <td><a href="{% url 'core:update2' team.id %}" class="btn btn-outline-warning"> Update</a></td>
                    <td><a href="{% url 'core:delete2' team.id %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

templates/core/list3.html
{% extends 'base/base.html' %}

{% block title %} LIST STADIUM {% endblock title %}

{% block content %}


    <a href="{% url 'core:create3' %}" class="btn btn-outline-success form-control">add stadium</a>
    <table class="table table-striped table-hover">
        <thead>
            
            <th>NAME STADIUM</th>
            <th>DESCRIPTION</th> 
            <th>LOCATION</th>
        </thead>
        <tbody>
            {% for stadium in stadium %}
                <tr>
                    <td>{{ stadium.name3 }}</td>
                    <td>{{ stadium.description2 }}</td>
                    <td>{{ stadium.location }}</td>
                   
                    <td><a href="{% url 'core:detail3' stadium.id %}" class="btn btn-outline-info"> Detail </a></td>
                    <td><a href="{% url 'core:update3' stadium.id %}" class="btn btn-outline-warning"> Update</a></td>
                    <td><a href="{% url 'core:delete3' stadium.id %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

templates/core/update1.html
{% extends "base/base.html" %}

{% block title %}
  UPDATE CITY
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Update city</button>
        <a href="{% url 'core:list1' %}" class="btn btn-outline-warning">Cancel</a>
    </form>

{% endblock content %}

templates/core/update3.html
{% extends "base/base.html" %}

{% block title %}
  UPDATE STADIUM
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Update stadium</button>
        <a href="{% url 'core:list3' %}" class="btn btn-outline-warning">Cancel</a>
    </form>

{% endblock content %}